services:
  - type: web
    name: blinkit-intelligence
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SYPHOON_PRODUCT_KEY
        value: AJrvtM4v4viAmLFzyvG
      - key: SYPHOON_CATEGORY_KEY
        value: BWE8UD59KJMnz9Nj9aMD
      - key: SYPHOON_KEYWORD_KEY
        value: VfPabFvyIHZZYGTpIlDL
      - key: APP_ENV
        value: production
      - key: CORS_ORIGINS
        value: "*"
